name: CI/CD Pipeline to Digital Oceans
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:
  #Test's job
  tests:
    name: Unit tests
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's step
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v1
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      #Run Tests
      - name: Run Tests
        run: mvn -B test
  #We using SonarCloud.io for Catch bug and code Error
  sonar:
    #Need tests jobs
    needs: tests
    name: SonarCloud Code Analysis
    runs-on: ubuntu-latest
    #Job Step
    steps:
      #Checkout Repository
      - uses: actions/checkout@v2
      #Setup JDK
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      #Analyze Code with SonarCloud
      - name: Analyze With SonarCloud
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=gilangjavier_episode02-ci-cd-digitaloceans
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #build Stage
  build:
    name: Build Artifact
    needs: sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
    #Build Application Using Maven
      - name: Build with maven
        run: mvn -B package -DskipTests --file pom.xml
      #BUILD THE ARTIFACT
      - name: Upload War Artifact
        #This upload our artifacts from workflow allowing to share data between jobs and store data once a workflow is complete.
        uses: actions/upload-artifact@v2
        with:
          #set artifact name
          name: artifact
          #From:
          path: target/*.war
  deploy:
    #Need Build Jobs success
    needs: build
    name : Deploy to Digital Ocean Droplet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: path/to/artifact
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifact
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: ~/home/runner/work/episode02-ci-cd-digitaloceans/episode02-ci-cd-digitaloceans/path/to/artifact/*.war
          remote: /opt/tomcat/webapps/ROOT/ROOT.war
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}

